# Your workflow name.
name: Deploy to render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflow's jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Render
        uses: bounceapp/render-action@0.6.0
        with:
          github-token: ${{ secrets.RENDER_TOKEN }} # Correct the secret name if it's different
          service-id: srv-cm9nkhud3nmc73cs6rt0
          retries: 20
          wait: 16000
          sleep: 30000
### ⬆ IMPORTANT PART ⬆ ###
