name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: sws2apps/render-deployment@main 
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
