name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: sws2apps/render-deployment@main 
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: https://api.render.com/deploy/srv-cm9nkhud3nmc73cs6rt0?key=NA3PWPR1fxY
