# Your workflow name.
name: Deploy to render.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Render. # Your custom step name
        uses: bounceapp/render-action@0.6.0 # GitHub action name (leave it as it is).
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cm9nkhud3nmc73cs6rt0
          retries: 20
          wait: 16000
          sleep: 30000
### ⬆ IMPORTANT PART ⬆ ###
